name: Python package

on:
  pull_request:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 */5 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get -o Acquire::Retries=3 update
        sudo apt-get -o Acquire::Retries=3 install *fftw3* mpi intel-mkl*
        python -m pip install tox pip setuptools notebook --upgrade
        python -m pip install pycbc ligo-common
    - name: Run notebooks scripts to make sure they can be run
      run: |
        ./test_notebooks
